apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: Build
  metadata:
    annotations:
      openshift.io/build-config.name: spring-boot-camel-complete-s2i
      openshift.io/build.number: "7"
      openshift.io/build.pod-name: spring-boot-camel-complete-s2i-7-build
    labels:
      app: spring-boot-camel-complete
      buildconfig: spring-boot-camel-complete-s2i
      group: org.eclipse.jkube.quickstarts.maven
      openshift.io/build-config.name: spring-boot-camel-complete-s2i
      openshift.io/build.start-policy: Serial
      provider: jkube
      version: 1.9.1
    name: spring-boot-camel-complete-s2i-7
    namespace: rhn-support-weihuang-dev
  spec:
    nodeSelector: null
    output:
      pushSecret:
        name: builder-dockercfg-s5c8m
      to:
        kind: ImageStreamTag
        name: spring-boot-camel-complete:1.9.1
    serviceAccount: builder
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: quay.io/jkube/jkube-java:0.0.16
        pullSecret:
          name: pullsecret-jkube
      type: Source
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
